name       : icestorm
version    : 0.1.0
release    : 2
source     :
    - https://github.com/YosysHQ/icestorm/archive/refs/heads/master.zip : f72188d7c75b9c127b6ce696b4e47e3224a5fa6b2ff1458f3f0d1ab303d168fc
license    : ISC
summary    : A collection of tools and documentation for iCE40 FPGAs.
description: |
    Project IceStorm aims at documenting the bitstream format of Lattice iCE40 FPGAs and providing simple tools for analyzing and creating bitstream files.
    See https://clifford.at/icestorm for more information.
component  : office.scientific
strip      : no
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(libffi)
    - pkgconfig(libftdi1)
    - pkgconfig(python3)
    - pkgconfig(readline)
    - pkgconfig(tcl)
    - libboost-devel
    - graphviz
    - qt5-base
environment: |
    export PREFIX=/usr
build      : |
    %make 
install    : |
    %make_install
    install -dm00644 $installdir/usr/bin/
    install -dm00644 $installdir/usr/share/icebox
    install -Dm00644 $pkgfiles/53-lattice-ftdi.rules /$installdir/etc/udev/rules.d/53-lattice-ftdi.rules